#데이터베이스 연결 설정
spring:
  datasource:
    url: jdbc:mysql://mutsa-db.c70gmyqsgx70.ap-northeast-2.rds.amazonaws.com:3306/mutsa_board
    username: wooh
    password: dngur1213
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  address: 0.0.0.0
